service: deepl-translate

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  httpApi:
    cors: true
  environment:
    DEEPL_API_KEY: ${env:DEEPL_API_KEY}

functions:
  hello:
    handler: handler.translate
    events:
      - httpApi:
          path: /
          method: post

package:
  patterns:
    - '!node_modules/**'
    - '!.gitignore'
    - '!package.json'
    - '!pnpm-lock.yaml'
    - '!README.md'
    - 'handler.js'
